/* eslint-disable global-require */

const Images = {
  arrowRight: require('../assets/arrow_right.png'),
  block: require('../assets/block.png'),
  blueLocation: require('../assets/blue-location.png'),
  calendar: require('../assets/calendar.png'),
  check: require('../assets/check2x.png'),
  checkbox: require('../assets/checkbox2x.png'),
  checkmark: require('../assets/checkmark2x.png'),
  checkoff: require('../assets/checkoff2x.png'),
  close: require('../assets/close2x.png'),
  coaching: require('../assets/coaching.png'),
  email: require('../assets/mail2x.png'),
  eyeoff: require('../assets/eyeoff2x.png'),
  eyeon: require('../assets/eye2x.png'),
  fb: require('../assets/fb2x.png'),
  filter: require('../assets/filters.png'),
  greenLocation: require('../assets/green-location.png'),
  insta: require('../assets/insta2x.png'),
  intro1: require('../assets/w1_img.png'),
  intro2: require('../assets/w2_img.png'),
  intro3: require('../assets/w3_img.png'),
  line: require('../assets/Line2x.png'),
  live: require('../assets/live.png'),
  location: require('../assets/location.png'),
  lock: require('../assets/lock.png'),
  logo: require('../assets/logo.png'),
  map: require('../assets/map.png'),
  mapPin: require('../assets/map-pin.png'),
  myLocation: require('../assets/my-location.png'),
  notifications: require('../assets/notifications.png'),
  path1: require('../assets/Path46.png'),
  path2: require('../assets/Path47.png'),
  racing: require('../assets/stopwatch.png'),
  report: require('../assets/report.png'),
  search: require('../assets/search.png'),
  slectLangLogo2x: require('../assets/slectLangLogo2x.png'),
  tabBarAdd: require('../assets/tabbar_add.png'),
  tabBarChat: require('../assets/tabbar_chat.png'),
  tabBarFeed: require('../assets/tabbar_feed.png'),
  tabBarHome: require('../assets/tabbar_home.png'),
  tabBarProfile: require('../assets/tabbar_profile.png'),
  tiktok: require('../assets/tiktok2x.png'),
  toggleOff: require('../assets/toggle_off.png'),
  toggleOn: require('../assets/toggle_on.png'),
  training: require('../assets/female.png'),
  twitter: require('../assets/twitter2x.png'),
  yellowLocation: require('../assets/yellow-location.png'),
};

module.exports = Images;
