/* eslint-disable global-require */

const Images = {
  check: require('../assets/check2x.png'),
  checkbox: require('../assets/checkbox2x.png'),
  checkmark: require('../assets/checkmark2x.png'),
  checkoff: require('../assets/checkoff2x.png'),
  close: require('../assets/close2x.png'),
  email: require('../assets/mail2x.png'),
  eyeoff: require('../assets/eyeoff2x.png'),
  eyeon: require('../assets/eye2x.png'),
  fb: require('../assets/fb2x.png'),
  filter: require('../assets/filters.png'),
  insta: require('../assets/insta2x.png'),
  intro1: require('../assets/w1_img.png'),
  intro2: require('../assets/w2_img.png'),
  intro3: require('../assets/w3_img.png'),
  line: require('../assets/Line2x.png'),
  location: require('../assets/location.png'),
  logo: require('../assets/logo.png'),
  map: require('../assets/map.png'),
  notifications: require('../assets/notifications.png'),
  path1: require('../assets/Path46.png'),
  path2: require('../assets/Path47.png'),
  search: require('../assets/search.png'),
  slectLangLogo2x: require('../assets/slectLangLogo2x.png'),
  tabBarAdd: require('../assets/tabbar_add.png'),
  tabBarChat: require('../assets/tabbar_chat.png'),
  tabBarFeed: require('../assets/tabbar_feed.png'),
  tabBarHome: require('../assets/tabbar_home.png'),
  tabBarProfile: require('../assets/tabbar_profile.png'),
  tiktok: require('../assets/tiktok2x.png'),
  twitter: require('../assets/twitter2x.png'),
};

module.exports = Images;
