/* eslint-disable import/no-unresolved */
/* eslint-disable sort-keys */
/* eslint-disable global-require */

const Images = {
  check: require('../assets/check2x.png'),
  checkbox: require('../assets/checkbox2x.png'),
  checkmark: require('../assets/checkmark2x.png'),
  checkoff: require('../assets/checkoff2x.png'),
  close: require('../assets/close2x.png'),
  email: require('../assets/mail2x.png'),
  eyeoff: require('../assets/eyeoff2x.png'),
  eyeon: require('../assets/eye2x.png'),
  fb: require('../assets/fb2x.png'),
  filter: require('../assets/filters.png'),
  insta: require('../assets/insta2x.png'),
  intro1: require('../assets/w1_img.png'),
  intro2: require('../assets/w2_img.png'),
  intro3: require('../assets/w3_img.png'),
  line: require('../assets/Line2x.png'),
  location: require('../assets/location.png'),
  logo: require('../assets/logo.png'),
  map: require('../assets/map.png'),
  notifications: require('../assets/notifications.png'),
  path1: require('../assets/Path46.png'),
  path2: require('../assets/Path47.png'),
  search: require('../assets/search.png'),
  slectLangLogo2x: require('../assets/slectLangLogo2x.png'),
  tabBarAdd: require('../assets/tabbar_add.png'),
  tabBarChat: require('../assets/tabbar_chat.png'),
  tabBarFeed: require('../assets/tabbar_feed.png'),
  tabBarHome: require('../assets/tabbar_home.png'),
  tabBarProfile: require('../assets/tabbar_profile.png'),
  tiktok: require('../assets/tiktok2x.png'),
  twitter: require('../assets/twitter2x.png'),
  Screenshot: require('../assets/Screenshot.png'),
  closeRound: require('../assets/closeRound.png'),
  chat: require('../assets/chat.png'),
  addFriend: require('../assets/addFriend.png'),
  threeDots: require('../assets/threeDots.png'),
  lockProfile: require('../assets/lockProfile.png'),
  profilePic: require('../assets/profilePic.png'),
  goal1: require('../assets/goal1.png'),
  goal2: require('../assets/goal2.png'),
  goal3: require('../assets/goal3.png'),
  videoIcon: require('../assets/videoIcon.png'),
  settings: require('../assets/settings.png'),
};

module.exports = Images;
